[release_target]
# ここをプログラムから上書き、またはここに直接書く
target_src = default_app


release_dir = {target_src}
apps_structure = apps/{target_src}
common_structure = common
config = {apps_structure}/config.ini
py_file = {apps_structure}/main.py
exe_file = {apps_structure}/dist/main.exe
icon_file = {apps_structure}/icon_01.ico


apps_list = 
	apps/{target_src}/*.py
	apps/{target_src}/*.ico
	apps/{target_src}/dist/*.exe
	common