[release_target]
# 以下のpathを読み込み、リリース対象のリストを取得
path = apps

# ここをプログラムから上書き、またはここに直接書く
# すでに ExtendedInterpolation を使っている場合は .format は不要ですが、そうでない場合は .format を使って展開する必要があります。
# 今は未使用
target_src = default_app

# コピー対象のリスト
release_list = 
    # [元パス] > [コピー先パス（アプリフォルダからの相対）]
    # コピー対象がない場合もエラーにしない
    %(path)s/{target_src}/main.py > apps/{target_src}/deff.py
    %(path)s/{target_src}/main.py > apps/{target_src}/regex.py
    %(path)s/{target_src}/main.py > apps/{target_src}/treeviewer.py
    %(path)s/{target_src}/main.py > apps/{target_src}/csv_viewer.py
    %(path)s/{target_src}/main.py > apps/{target_src}/json_viewer.py
    %(path)s/{target_src}/main.py > apps/{target_src}/xml_viewer.py
    %(path)s/{target_src}/main.py > apps/{target_src}/db_viewer.py
    %(path)s/{target_src}/main.py > apps/{target_src}/main.py
    %(path)s/{target_src}/icon_01.ico > apps/{target_src}/icon_01.ico
    %(path)s/{target_src}/config.ini > apps/{target_src}/config.ini
    common > common
    # exeファイルだけ直下（./）に配置
    %(path)s/{target_src}/dist/main.exe > main.exe