[release_target]
# 以下のpathを読み込み、リリース対象のリストを取得
path = apps

# ここをプログラムから上書き、またはここに直接書く
# すでに ExtendedInterpolation を使っている場合は .format は不要ですが、そうでない場合は .format を使って展開する必要があります。
target_src = default_app

# コピー対象のリスト
release_list = 
    # [元パス] > [コピー先パス（アプリフォルダからの相対）]
    apps/{target_src}/main.py
    apps/{target_src}/icon_01.ico
    common
    # exeファイルだけ直下（./）に配置
    apps/{target_src}/dist/main.exe > main.exe